/*
 * 设备开放API
 *
 * worth open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package worth
// GenTokenResponseAllOf struct for GenTokenResponseAllOf
type GenTokenResponseAllOf struct {
	Data map[string]interface{} `json:"data,omitempty"`
}
