/*
 * 设备开放API
 *
 * worth open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package worth
// ActionReq struct for ActionReq
type ActionReq struct {
	DeviceId string `json:"device_id"`
	Data string `json:"data"`
	Charset string `json:"charset,omitempty"`
}
