/*
 * 设备开放API
 *
 * worth open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package worth
// ApiResponse 
type ApiResponse struct {
	Message string `json:"message,omitempty"`
	Code string `json:"code,omitempty"`
}
